"""SOAP power spectrum with analytic derivatives.

The Smooth Overlap of Atomic Positions descriptor represents the neighbour
density of atom ``i`` as a sum of Gaussians of width ``sigma_atom`` centred on
its neighbours,

.. math::

    \\rho_i(\\mathbf{r}) = \\sum_{j \\ne i} w_{s_j} f_c(r_{ij})
        \\exp\\!\\big[-\\alpha |\\mathbf{r} - \\mathbf{d}_{ij}|^2\\big],
    \\qquad \\alpha = \\frac{1}{2\\sigma_{\\rm atom}^2},

expands it in an orthonormal radial basis :math:`g_n(r)` and real spherical
harmonics :math:`Y_{lm}(\\hat{\\mathbf{r}})`,

.. math::  c^{(i)}_{nlm} = \\int g_n(r) Y_{lm}(\\hat{\\mathbf{r}})
                            \\rho_i(\\mathbf{r})\\, \\mathrm{d}^3 r,

and contracts the ``m`` index to obtain the rotationally invariant power
spectrum

.. math::  p^{(i)}_{n n' l} = \\frac{1}{\\sqrt{2l+1}}
                              \\sum_{m=-l}^{l} c^{(i)}_{nlm} c^{(i)}_{n'lm}.

Why this file is written the way it is
--------------------------------------

*The radial integral is done by quadrature, and the descriptor is defined to be
the quadrature sum.*  Using the plane-wave-like expansion of a displaced
Gaussian,

.. math::  e^{-\\alpha|\\mathbf{r}-\\mathbf{d}|^2} = e^{-\\alpha(r^2+d^2)}
           \\sum_{lm} 4\\pi\\, i_l(2\\alpha r d)\\, Y_{lm}(\\hat{\\mathbf{r}})
           Y_{lm}(\\hat{\\mathbf{d}}),

with :math:`i_l` the modified spherical Bessel function of the first kind, the
angular integral is exact and only a one-dimensional radial integral

.. math::  R_{nl}(d) = 4\\pi \\int_0^{r_{\\rm cut}} r^2 g_n(r)\\,
           e^{-\\alpha(r^2+d^2)} i_l(2\\alpha r d)\\, \\mathrm{d}r

remains.  There is no closed form for a polynomial ``g_n``, so it is evaluated
with fixed Gauss-Legendre quadrature.  Crucially the descriptor is *defined* as
that quadrature sum rather than as the exact integral it approximates, and the
analytic derivative is the exact derivative of the same sum.  Quadrature error
therefore shifts the feature definition slightly but never breaks the
derivative identity, which is the property the whole study depends on.

*The angular derivative goes through real solid harmonics, not through
spherical coordinates.*  ``dY_lm/dtheta`` has a coordinate singularity at
``theta = 0`` (the ``1/sin(theta)`` in ``dphi``), and neighbours sit on the
polar axis routinely in a cubic crystal.  Writing ``Y_lm(d_hat) = S_lm(d)/r^l``
with :math:`S_lm` the *real solid harmonic* -- a homogeneous polynomial in
``(x, y, z)`` of degree ``l`` -- makes the cartesian gradient a polynomial
identity that is regular everywhere except ``r = 0``.  The polynomial and its
gradient are generated by the same recurrence, carrying the gradient along, so
value and derivative cannot drift apart.

*Normalisation acquires a projection term.*  With
:math:`\\hat{p} = p / \\lVert p \\rVert`,

.. math::  \\frac{\\partial \\hat p}{\\partial x}
           = \\frac{1}{\\lVert p \\rVert}
             \\Big( \\mathbb{1} - \\hat p \\hat p^{\\mathsf T} \\Big)
             \\frac{\\partial p}{\\partial x} .

The projector is easy to forget, and forgetting it produces a descriptor
derivative that is wrong only in the component along ``p`` itself -- a small,
smooth error that a fit happily absorbs into its coefficients while quietly
corrupting every force.  That is exactly the failure mode this repository is
about, so the term is applied explicitly in :meth:`SOAP.compute` and checked
against finite differences in ``tests/test_soap.py``.

Cost
----

Defaults are ``n_max = 4``, ``l_max = 3``: 4 radial channels and ``l = 0..3``
give ``4 * n_max (n_max + 1) / 2 = 40`` invariant features.  This is far
smaller than a production SOAP (``n_max = 8-12``, ``l_max = 6-9``, thousands of
features) and is a deliberate scaling-down for a 4-core CPU budget: the study
needs a descriptor whose *error structure* is representative, not one whose
basis-set convergence is publishable.
"""

from __future__ import annotations

import math
from typing import Sequence

import numpy as np
from scipy.special import ive, sph_harm_y

from ...neighbors import build_neighbor_list, pair_vectors
from ...types import Configuration
from ..base import Descriptor, DescriptorOutput

__all__ = [
    "SOAP",
    "real_solid_harmonics",
    "real_spherical_harmonic_scipy",
    "polynomial_radial_basis",
    "segment_sum",
]


def segment_sum(values: np.ndarray, segment: np.ndarray, n_segments: int) -> np.ndarray:
    """Sum ``values`` over contiguous runs of equal ``segment`` label.

    Parameters
    ----------
    values : ndarray, shape (P, ...)
        Rows to be accumulated.
    segment : ndarray, shape (P,)
        Segment label of each row.  Must be **sorted non-decreasing**; the
        neighbour lists in :mod:`atomlab.neighbors` are canonically ordered by
        central atom, which is what makes this the natural reduction here.
    n_segments : int
        Number of output rows.  Segments with no rows give exactly zero.

    Returns
    -------
    ndarray, shape (n_segments,) + values.shape[1:]

    Notes
    -----
    Implemented as a difference of cumulative sums rather than with
    ``np.add.at``, which is an order of magnitude slower on the array sizes
    this descriptor produces, and rather than with ``np.add.reduceat``, which
    silently returns the wrong thing for empty segments (an atom with no
    neighbours inside the cutoff, which is a legitimate state in a dilute gas).
    """
    if values.shape[0] == 0:
        return np.zeros((n_segments,) + values.shape[1:], dtype=values.dtype)
    if np.any(np.diff(segment) < 0):
        raise ValueError("segment labels must be sorted non-decreasing")
    counts = np.bincount(segment, minlength=n_segments)
    ends = np.cumsum(counts)
    starts = ends - counts
    cum = np.zeros((values.shape[0] + 1,) + values.shape[1:], dtype=np.float64)
    np.cumsum(values, axis=0, out=cum[1:])
    return cum[ends] - cum[starts]


# --------------------------------------------------------------------------
# real spherical / solid harmonics
# --------------------------------------------------------------------------


def real_spherical_harmonic_scipy(l: int, m: int, directions: np.ndarray) -> np.ndarray:
    """Real spherical harmonic ``Y_lm`` evaluated with SciPy, for validation.

    Parameters
    ----------
    l : int
        Degree, ``l >= 0``.
    m : int
        Order, ``-l <= m <= l``.
    directions : ndarray, shape (P, 3)
        Cartesian vectors (angstrom, or any unit -- only the direction is
        used).  Must be nonzero.

    Returns
    -------
    ndarray, shape (P,)
        Dimensionless values of the real spherical harmonic, in the convention

        ``Y_l0     =            Y_l^0``
        ``Y_lm     = sqrt(2) (-1)^m Re Y_l^m``   (m > 0)
        ``Y_l,-m   = sqrt(2) (-1)^m Im Y_l^m``   (m > 0)

        with ``Y_l^m`` the complex harmonic.  The ``(-1)^m`` cancels the
        Condon-Shortley phase that SciPy includes, giving the phase-free
        convention used by the SOAP literature.

    Notes
    -----
    Uses ``scipy.special.sph_harm_y(n, m, theta, phi)`` with ``theta`` the
    **polar** angle and ``phi`` the azimuth -- the modern signature.  The legacy
    ``scipy.special.sph_harm`` (which took the arguments in the opposite order)
    was removed in SciPy 1.17, so it must not be used here.

    This routine is *not* used in the hot path; it is the independent reference
    that :func:`real_solid_harmonics` is checked against, because a wrong
    spherical-harmonic convention is precisely the bug that a rotational
    invariance test is designed to catch.
    """
    d = np.asarray(directions, dtype=np.float64).reshape(-1, 3)
    r = np.linalg.norm(d, axis=1)
    if np.any(r == 0.0):
        raise ValueError("cannot evaluate a spherical harmonic on a zero vector")
    theta = np.arccos(np.clip(d[:, 2] / r, -1.0, 1.0))  # polar angle in [0, pi]
    phi = np.arctan2(d[:, 1], d[:, 0])  # azimuth; sph_harm_y is 2*pi periodic in it
    y = sph_harm_y(int(l), int(abs(m)), theta, phi)
    if m == 0:
        return np.real(y)
    sign = (-1.0) ** abs(m)
    if m > 0:
        return math.sqrt(2.0) * sign * np.real(y)
    return math.sqrt(2.0) * sign * np.imag(y)


def _lm_index(l: int, m: int) -> int:
    """Flat index of ``(l, m)`` in the ``(l_max+1)**2`` packed ordering.

    Layout is ``l`` major, ``m`` running ``-l .. +l``, i.e. ``l*l + (m + l)``.
    """
    return l * l + (m + l)


def real_solid_harmonics(
    d: np.ndarray, l_max: int, *, gradient: bool = True
) -> tuple[np.ndarray, np.ndarray | None]:
    """Real solid harmonics ``S_lm(d) = |d|^l Y_lm(d_hat)`` and their gradients.

    Parameters
    ----------
    d : ndarray, shape (P, 3)
        Cartesian vectors in angstrom.
    l_max : int
        Maximum degree, ``>= 0``.
    gradient : bool
        Also return ``dS_lm / dd`` (cartesian).

    Returns
    -------
    S : ndarray, shape (P, (l_max+1)**2)
        Solid harmonics in units of ``A**l``, packed by :func:`_lm_index`.
    dS : ndarray, shape (P, (l_max+1)**2, 3) or None
        Cartesian gradient in units of ``A**(l-1)``.

    Notes
    -----
    Everything here is polynomial, hence regular at the poles ``x = y = 0``
    where the spherical-coordinate derivatives of ``Y_lm`` are singular.  The
    construction factors the solid harmonic as

    ``S_lm = K_lm * Pi_l^|m|(z, r^2) * {C_|m|(x,y) if m >= 0 else S_|m|(x,y)}``

    with ``C_m + i S_m = (x + i y)^m`` (built by the two-term recurrence
    ``C_m = x C_{m-1} - y S_{m-1}``, ``S_m = x S_{m-1} + y C_{m-1}``) and
    ``Pi`` the homogenised associated-Legendre polynomial obeying

    ``Pi_m^m = (2m-1)!!``,
    ``Pi_{m+1}^m = (2m+1) (2m-1)!! z``,
    ``(l-m) Pi_l^m = (2l-1) z Pi_{l-1}^m - (l+m-1) r^2 Pi_{l-2}^m``.

    The normalisation ``K_lm = sqrt((2l+1)/(4 pi) (l-|m|)!/(l+|m|)!)`` times
    ``sqrt(2)`` for ``m != 0`` reproduces the Condon-Shortley-free real
    harmonics of :func:`real_spherical_harmonic_scipy` exactly.

    Gradients are propagated through every recurrence step rather than derived
    by a closed formula, so the returned derivative is the exact derivative of
    the returned value by construction.
    """
    l_max = int(l_max)
    if l_max < 0:
        raise ValueError(f"l_max must be >= 0, got {l_max}")
    d = np.ascontiguousarray(np.asarray(d, dtype=np.float64).reshape(-1, 3))
    n_pairs = d.shape[0]
    x, y, z = d[:, 0], d[:, 1], d[:, 2]
    r2 = x * x + y * y + z * z

    n_lm = (l_max + 1) ** 2
    out = np.zeros((n_pairs, n_lm))
    dout = np.zeros((n_pairs, n_lm, 3)) if gradient else None

    # (x + i y)^m, split into real (Cm) and imaginary (Sm) parts.
    cm = np.zeros((l_max + 1, n_pairs))
    sm = np.zeros((l_max + 1, n_pairs))
    dcm = np.zeros((l_max + 1, n_pairs, 3))
    dsm = np.zeros((l_max + 1, n_pairs, 3))
    cm[0] = 1.0
    for m in range(1, l_max + 1):
        cm[m] = x * cm[m - 1] - y * sm[m - 1]
        sm[m] = x * sm[m - 1] + y * cm[m - 1]
        if gradient:
            dcm[m] = x[:, None] * dcm[m - 1] - y[:, None] * dsm[m - 1]
            dcm[m, :, 0] += cm[m - 1]
            dcm[m, :, 1] -= sm[m - 1]
            dsm[m] = x[:, None] * dsm[m - 1] + y[:, None] * dcm[m - 1]
            dsm[m, :, 0] += sm[m - 1]
            dsm[m, :, 1] += cm[m - 1]

    for m in range(0, l_max + 1):
        # (2m - 1)!!, with the empty product equal to 1 for m = 0.
        dfact = 1.0
        for k in range(1, 2 * m, 2):
            dfact *= k

        pi_lm2 = None
        dpi_lm2 = None
        pi_lm1 = np.full(n_pairs, dfact)  # l = m
        dpi_lm1 = np.zeros((n_pairs, 3))

        for l in range(m, l_max + 1):
            if l == m:
                pi = pi_lm1
                dpi = dpi_lm1
            elif l == m + 1:
                pi = (2 * m + 1) * dfact * z
                dpi = np.zeros((n_pairs, 3))
                dpi[:, 2] = (2 * m + 1) * dfact
            else:
                inv = 1.0 / (l - m)
                pi = ((2 * l - 1) * z * pi_lm1 - (l + m - 1) * r2 * pi_lm2) * inv
                if gradient:
                    dpi = (
                        (2 * l - 1) * z[:, None] * dpi_lm1
                        - (l + m - 1) * (r2[:, None] * dpi_lm2 + 2.0 * d * pi_lm2[:, None])
                    ) * inv
                    dpi[:, 2] += (2 * l - 1) * pi_lm1 * inv
                else:
                    dpi = None

            # K_lm = sqrt((2l+1)/(4 pi) * (l-m)!/(l+m)!), with sqrt(2) for m != 0.
            norm = math.sqrt(
                (2 * l + 1)
                / (4.0 * math.pi)
                * math.factorial(l - m)
                / math.factorial(l + m)
            )
            if m > 0:
                norm *= math.sqrt(2.0)

            idx = _lm_index(l, m)
            out[:, idx] = norm * pi * cm[m]
            if gradient:
                dout[:, idx, :] = norm * (dpi * cm[m][:, None] + pi[:, None] * dcm[m])
            if m > 0:
                idx_neg = _lm_index(l, -m)
                out[:, idx_neg] = norm * pi * sm[m]
                if gradient:
                    dout[:, idx_neg, :] = norm * (
                        dpi * sm[m][:, None] + pi[:, None] * dsm[m]
                    )

            pi_lm2, dpi_lm2 = pi_lm1, dpi_lm1
            pi_lm1, dpi_lm1 = pi, dpi

    return out, dout


# --------------------------------------------------------------------------
# radial basis
# --------------------------------------------------------------------------


def polynomial_radial_basis(n_max: int, r_cut: float) -> np.ndarray:
    """Orthonormalising transform for the GAP polynomial radial basis.

    The primitive basis is ``phi_n(r) = (r_cut - r)**(n + 2)`` for
    ``n = 1 .. n_max``.  Two properties make it the standard GAP choice and are
    worth stating explicitly:

    * every ``phi_n`` and its first two derivatives vanish **exactly** at
      ``r_cut`` (the exponent is at least 3), so nothing has to be smoothed by
      hand at the cutoff;
    * the Gram matrix under the radial measure ``r^2 dr`` is available in closed
      form,

      ``S_nm = int_0^rc r^2 phi_n phi_m dr
             = rc^(n+m+7) * 2 / ((n+m+5)(n+m+6)(n+m+7))``

      so the orthonormalisation carries no quadrature error of its own.

    Parameters
    ----------
    n_max : int
        Number of radial functions, ``>= 1``.
    r_cut : float
        Cutoff radius in angstrom.

    Returns
    -------
    ndarray, shape (n_max, n_max)
        The matrix ``W = S^(-1/2)`` with ``g_n(r) = sum_m W[n, m] phi_{m+1}(r)``
        satisfying ``int_0^rc r^2 g_n g_n' dr = delta_{nn'}``.  Units of
        ``g_n`` are ``A^(-3/2)``.

    Notes
    -----
    ``S`` is a Hilbert-like matrix and its condition number grows quickly with
    ``n_max``; at the default ``n_max = 4`` it is ~1e4, which double precision
    handles comfortably.  A warning-free ``n_max`` above ~10 would need a
    genuinely orthogonal primitive basis instead, and this project has no use
    for one.
    """
    n_max = int(n_max)
    if n_max < 1:
        raise ValueError(f"n_max must be >= 1, got {n_max}")
    r_cut = float(r_cut)
    if r_cut <= 0.0:
        raise ValueError(f"r_cut must be > 0 A, got {r_cut}")

    idx = np.arange(1, n_max + 1)
    k = idx[:, None] + idx[None, :]  # n + m
    gram = r_cut ** (k + 7.0) * 2.0 / ((k + 5.0) * (k + 6.0) * (k + 7.0))
    # Symmetric positive definite by construction; use the eigendecomposition
    # rather than a Cholesky inverse so that near-degenerate directions are
    # visible as tiny eigenvalues instead of a spurious failure.
    evals, evecs = np.linalg.eigh(gram)
    if np.any(evals <= 0.0):
        raise np.linalg.LinAlgError(
            f"radial Gram matrix is not positive definite for n_max={n_max}; "
            "the polynomial basis has become numerically degenerate"
        )
    return (evecs / np.sqrt(evals)) @ evecs.T


def _radial_basis_values(n_max: int, r_cut: float, weights: np.ndarray, r: np.ndarray):
    """Evaluate ``g_n(r)`` on a grid.

    Parameters
    ----------
    n_max, r_cut : see :func:`polynomial_radial_basis`
    weights : ndarray, shape (n_max, n_max)
        The transform from :func:`polynomial_radial_basis`.
    r : ndarray, shape (Q,)
        Radii in angstrom.

    Returns
    -------
    ndarray, shape (n_max, Q)
        ``g_n(r_q)`` in ``A^(-3/2)``.
    """
    powers = np.arange(1, n_max + 1) + 2.0
    phi = np.power(np.maximum(r_cut - r, 0.0)[None, :], powers[:, None])
    return weights @ phi


# --------------------------------------------------------------------------
# modified spherical Bessel functions, exponentially scaled
# --------------------------------------------------------------------------


def _scaled_bessel_i(l_max: int, u: np.ndarray) -> np.ndarray:
    """``exp(-u) * i_l(u)`` for ``l = 0 .. l_max``, where ``i_l`` is modified
    spherical Bessel of the first kind.

    Parameters
    ----------
    l_max : int
        Highest order required.
    u : ndarray
        Non-negative arguments, ``u = 2 * alpha * r * d``.

    Returns
    -------
    ndarray, shape u.shape + (l_max + 1,)
        Dimensionless.

    Notes
    -----
    ``i_l(u) = sqrt(pi / 2u) I_{l+1/2}(u)`` grows like ``e^u / 2u``, which
    overflows double precision at ``u ~ 700``.  With ``alpha = 1/(2 sigma^2)``,
    ``sigma = 0.3 A`` and ``r = d = 5 A`` we already have ``u ~ 280``, so the
    unscaled function is not merely inelegant here but actually unusable.  The
    factor ``e^{-alpha(r^2+d^2)}`` that multiplies it in the SOAP integrand
    supplies exactly the compensating decay, and the two are combined
    analytically as ``e^{-alpha(r-d)^2} * [e^{-u} i_l(u)]`` before anything is
    evaluated numerically.  ``scipy.special.ive`` is the exponentially scaled
    modified Bessel function ``I_nu(u) e^{-|u|}``, so it delivers the bracket
    directly.
    """
    u = np.asarray(u, dtype=np.float64)
    # u = 0 makes the sqrt(pi/2u) prefactor singular even though the product is
    # finite; the floor is far below any physically reachable pair separation
    # times a quadrature node, and keeps the expression branch-free.
    u_safe = np.maximum(u, 1e-12)
    orders = np.arange(l_max + 1) + 0.5
    scaled = ive(orders, u_safe[..., None])
    return np.sqrt(0.5 * math.pi / u_safe)[..., None] * scaled


# --------------------------------------------------------------------------
# the descriptor
# --------------------------------------------------------------------------


class SOAP(Descriptor):
    """SOAP power spectrum with exact analytic position derivatives.

    Parameters
    ----------
    r_cut : float
        Cutoff radius in angstrom.  Default 5.0.
    n_max : int
        Number of orthonormal radial basis functions.  Default 4.
    l_max : int
        Maximum spherical-harmonic degree; ``l`` runs ``0 .. l_max``.
        Default 3.
    sigma_atom : float
        Width in angstrom of the Gaussian placed on each neighbour.  Default
        0.5.  Smaller values sharpen the density and demand more quadrature
        nodes; larger values wash out radial structure.
    n_quadrature : int
        Number of Gauss-Legendre nodes used for the radial overlap integral
        ``R_nl``.  Default 48.  This controls how faithfully the features
        approximate the ideal SOAP integral; it has **no** effect on the
        exactness of the derivatives, on rotational invariance, or on any other
        symmetry, because the descriptor is defined as the quadrature sum.
    normalize : bool
        Scale each atom's feature vector to unit Euclidean length.  Default
        True.  See the module docstring for the projection term this adds to
        the derivative.
    species_weights : sequence of float, optional
        Multiplicative weight per species index applied to that species'
        contribution to the density.  ``None`` (default) weights every
        neighbour equally, which is what the single-species systems in this
        study need.  This is the cheap way to carry chemistry: a proper
        multi-species SOAP would give each species its own set of ``c_nlm``
        channels and square the feature count.
    name : str
        Identifier used in tables and figures.

    Attributes
    ----------
    cutoff : float
        Interaction range in angstrom, equal to ``r_cut``.
    n_features : int
        ``(l_max + 1) * n_max * (n_max + 1) / 2``.  For the defaults
        ``n_max = 4``, ``l_max = 3`` this is 40.

    Notes
    -----
    Feature ordering is ``l`` major, then the upper triangle ``n <= n'`` in
    row-major order:  ``(l=0, n=1, n'=1), (l=0, n=1, n'=2), ...``.  Off-diagonal
    terms ``n < n'`` appear once and are *not* multiplied by ``sqrt(2)``; the
    resulting vector is still a complete set of invariants and any constant
    per-feature rescaling is absorbed by the model that consumes it.

    Units: ``g_n`` is normalised against the measure ``r^2 dr`` and so carries
    ``A^(-3/2)``; integrating it against the (dimensionless) density over
    ``d^3 r`` leaves ``c_nlm`` in ``A^(3/2)`` and the unnormalised power
    spectrum in ``A^3``.  After ``normalize=True`` the features are
    dimensionless.
    """

    def __init__(
        self,
        r_cut: float = 5.0,
        n_max: int = 4,
        l_max: int = 3,
        sigma_atom: float = 0.5,
        *,
        n_quadrature: int = 48,
        normalize: bool = True,
        species_weights: Sequence[float] | None = None,
        name: str = "soap",
        chunk_size: int = 4096,
    ) -> None:
        self.cutoff = float(r_cut)
        if self.cutoff <= 0.0:
            raise ValueError(f"r_cut must be > 0 A, got {r_cut}")
        self.n_max = int(n_max)
        self.l_max = int(l_max)
        if self.n_max < 1:
            raise ValueError(f"n_max must be >= 1, got {n_max}")
        if self.l_max < 0:
            raise ValueError(f"l_max must be >= 0, got {l_max}")
        self.sigma_atom = float(sigma_atom)
        if self.sigma_atom <= 0.0:
            raise ValueError(f"sigma_atom must be > 0 A, got {sigma_atom}")
        self.n_quadrature = int(n_quadrature)
        if self.n_quadrature < 4:
            raise ValueError(f"n_quadrature must be >= 4, got {n_quadrature}")
        self.normalize = bool(normalize)
        self.species_weights = (
            None if species_weights is None else np.asarray(species_weights, dtype=np.float64)
        )
        self.name = str(name)
        self.chunk_size = int(chunk_size)
        if self.chunk_size < 1:
            raise ValueError(f"chunk_size must be >= 1, got {chunk_size}")

        self.alpha = 0.5 / (self.sigma_atom * self.sigma_atom)

        # -- fixed quadrature grid and radial basis, built once ------------
        nodes, weights = np.polynomial.legendre.leggauss(self.n_quadrature)
        self._r_quad = 0.5 * self.cutoff * (nodes + 1.0)
        w_quad = 0.5 * self.cutoff * weights
        self._basis_transform = polynomial_radial_basis(self.n_max, self.cutoff)
        g = _radial_basis_values(self.n_max, self.cutoff, self._basis_transform, self._r_quad)
        # Fold the measure r^2 dr and the 4*pi of the Gaussian expansion into
        # the weights, so the pair loop is a single contraction.
        self._quad_weights = (4.0 * math.pi) * g * (w_quad * self._r_quad**2)[None, :]

        # -- feature index bookkeeping -------------------------------------
        pairs = [(n, m) for n in range(self.n_max) for m in range(n, self.n_max)]
        self._pair_n = np.array([p[0] for p in pairs], dtype=np.intp)
        self._pair_m = np.array([p[1] for p in pairs], dtype=np.intp)
        self._n_features = (self.l_max + 1) * len(pairs)

    # -- introspection ----------------------------------------------------

    @property
    def n_features(self) -> int:
        """Descriptor dimension per atom."""
        return self._n_features

    def feature_labels(self) -> list[str]:
        """Human-readable ``(l, n, n')`` label for every feature, in order."""
        out: list[str] = []
        for l in range(self.l_max + 1):
            for n, m in zip(self._pair_n, self._pair_m):
                out.append(f"l{l}_n{int(n) + 1}_n{int(m) + 1}")
        return out

    def __repr__(self) -> str:  # pragma: no cover - cosmetic
        return (
            f"SOAP(r_cut={self.cutoff}, n_max={self.n_max}, l_max={self.l_max}, "
            f"sigma_atom={self.sigma_atom}, n_features={self.n_features})"
        )

    # -- pieces of the calculation ----------------------------------------

    def _cutoff_function(self, r: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        """Cosine cutoff ``0.5 (1 + cos(pi r / rc))`` and its derivative.

        Both the function and its first derivative vanish at ``r_cut``, so a
        neighbour entering or leaving the sphere contributes no discontinuity to
        the descriptor or to the force.  The radial basis vanishes at ``r_cut``
        too, but that does not help here: ``R_nl(d)`` is an *integral* over the
        basis, not an evaluation of it, and is nonzero at ``d = r_cut``.

        Returns arrays of shape ``r.shape``; ``f`` dimensionless, ``df`` in
        ``1/A``.
        """
        s = math.pi / self.cutoff
        f = 0.5 * (1.0 + np.cos(s * r))
        df = -0.5 * s * np.sin(s * r)
        outside = r >= self.cutoff
        f = np.where(outside, 0.0, f)
        df = np.where(outside, 0.0, df)
        return f, df

    def _radial_overlap(self, r_pair: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        """``R_nl(d)`` and ``dR_nl/dd`` for a batch of pair distances.

        Parameters
        ----------
        r_pair : ndarray, shape (P,)
            Pair distances ``d`` in angstrom.

        Returns
        -------
        R : ndarray, shape (P, n_max, l_max + 1)
            Radial overlap integrals, units ``A^(3/2)``.
        dR : ndarray, shape (P, n_max, l_max + 1)
            ``dR/dd`` in ``A^(1/2)``.

        Notes
        -----
        The integrand is written as

        ``r^2 g_n(r) * exp(-alpha (r - d)^2) * h_l(2 alpha r d)``,
        ``h_l(u) = e^{-u} i_l(u)``,

        which is the numerically safe regrouping described in
        :func:`_scaled_bessel_i`.  Differentiating under the integral sign,

        ``d/dd [exp(-alpha (r-d)^2) h_l] =
             exp(-alpha (r-d)^2) * 2 alpha [ (r - d) h_l + r h_l' ]``

        and ``h_l'(u) = [l h_{l-1}(u) + (l+1) h_{l+1}(u)] / (2l+1) - h_l(u)``,
        which follows from ``i_l' = [l i_{l-1} + (l+1) i_{l+1}]/(2l+1)`` and the
        product rule on the ``e^{-u}`` factor.  This is why ``h`` is evaluated
        up to order ``l_max + 1``.
        """
        alpha = self.alpha
        rq = self._r_quad  # (Q,)
        d = r_pair[:, None]  # (P, 1)

        gauss = np.exp(-alpha * (rq[None, :] - d) ** 2)  # (P, Q)
        u = (2.0 * alpha) * rq[None, :] * d  # (P, Q)
        h = _scaled_bessel_i(self.l_max + 1, u)  # (P, Q, l_max + 2)

        ell = np.arange(self.l_max + 1)
        h_lo = np.concatenate([np.zeros(h.shape[:-1] + (1,)), h[..., : self.l_max]], axis=-1)
        dh = (
            ell * h_lo + (ell + 1.0) * h[..., 1 : self.l_max + 2]
        ) / (2.0 * ell + 1.0) - h[..., : self.l_max + 1]

        core = gauss[..., None] * h[..., : self.l_max + 1]  # (P, Q, L+1)
        dcore = gauss[..., None] * (
            (2.0 * alpha)
            * (
                (rq[None, :, None] - d[..., None]) * h[..., : self.l_max + 1]
                + rq[None, :, None] * dh
            )
        )

        r_nl = np.einsum("nq,pql->pnl", self._quad_weights, core, optimize=True)
        dr_nl = np.einsum("nq,pql->pnl", self._quad_weights, dcore, optimize=True)
        return r_nl, dr_nl

    def _pair_expansion(self, dvec: np.ndarray, r: np.ndarray, derivatives: bool):
        """Per-pair contribution to ``c_nlm`` and its cartesian gradient.

        Parameters
        ----------
        dvec : ndarray, shape (P, 3)
            Pair displacement vectors ``d_ij = r_j - r_i`` in angstrom.
        r : ndarray, shape (P,)
            ``|d_ij|`` in angstrom.
        derivatives : bool

        Returns
        -------
        contrib : ndarray, shape (P, n_max, (l_max+1)**2)
            ``A_nl(r) * Y_lm(d_hat)`` in ``A^(3/2)``, where
            ``A_nl = R_nl * f_cut``.
        dcontrib : ndarray, shape (P, n_max, (l_max+1)**2, 3) or None
            ``d/dd`` of the above, in ``A^(1/2)``.

        Notes
        -----
        The whole point of the solid-harmonic route appears here.  Writing
        ``A_nl(r) Y_lm(d_hat) = B_nl(r) S_lm(d)`` with ``B_nl = A_nl / r^l``,

        ``grad [B_nl S_lm] = B_nl'(r) (d / r) S_lm(d) + B_nl(r) grad S_lm(d)``

        which never divides by ``sin(theta)`` and is therefore finite for every
        neighbour direction including the poles.
        """
        r_nl, dr_nl = self._radial_overlap(r)  # (P, n, L+1)
        f_cut, df_cut = self._cutoff_function(r)

        a_nl = r_nl * f_cut[:, None, None]
        da_nl = dr_nl * f_cut[:, None, None] + r_nl * df_cut[:, None, None]

        # B_nl = A_nl / r^l  and  B_nl' = A_nl'/r^l - l A_nl / r^(l+1).
        ell = np.arange(self.l_max + 1)
        inv_rl = r[:, None, None] ** (-ell[None, None, :].astype(np.float64))
        b_nl = a_nl * inv_rl
        db_nl = (da_nl - ell[None, None, :] * a_nl / r[:, None, None]) * inv_rl

        solid, dsolid = real_solid_harmonics(dvec, self.l_max, gradient=derivatives)

        # Expand the (l) axis of B to the packed (l, m) axis.
        l_of_lm = np.concatenate([np.full(2 * l + 1, l) for l in range(self.l_max + 1)])
        b_lm = b_nl[:, :, l_of_lm]  # (P, n, LM)
        contrib = b_lm * solid[:, None, :]

        if not derivatives:
            return contrib, None

        db_lm = db_nl[:, :, l_of_lm]
        dhat = dvec / r[:, None]
        dcontrib = (
            db_lm[..., None] * solid[:, None, :, None] * dhat[:, None, None, :]
            + b_lm[..., None] * dsolid[:, None, :, :]
        )
        return contrib, dcontrib

    # -- the public entry point -------------------------------------------

    def compute(
        self, configuration: Configuration, *, derivatives: bool = True
    ) -> DescriptorOutput:
        """Featurise every atom of ``configuration``.

        Parameters
        ----------
        configuration : Configuration
            Geometry; not modified.
        derivatives : bool
            Also return ``dp/dr`` in the sparse pair layout of
            :class:`~atomlab.models.base.DescriptorOutput`.

        Returns
        -------
        DescriptorOutput
            ``features`` is ``(N, n_features)``; with ``normalize=True`` it is
            dimensionless, otherwise ``A^3``.  ``derivatives`` is
            ``(P + N, n_features, 3)`` in ``1/A`` (or ``A^2`` unnormalised):
            one block per neighbour pair, giving ``dp_i / dr_j``, followed by
            one block per atom giving the self term ``dp_i / dr_i``.

        Notes
        -----
        A pair ``(i, j)`` seen through several periodic images appears several
        times in the pair list, and the corresponding derivative blocks simply
        appear several times as well; the assembly in
        :meth:`DescriptorOutput.forces_from_energy_gradient` uses ``np.add.at``
        and therefore sums them, which is exactly right.

        Atoms with no neighbours inside the cutoff get a zero feature vector.
        With ``normalize=True`` that vector cannot be scaled to unit length, so
        it is left at zero rather than being divided by zero, and its
        derivatives are zero too.  This is a real state (an isolated atom in a
        dilute gas), not an error.
        """
        n_atoms = configuration.n_atoms
        nl = build_neighbor_list(configuration, self.cutoff, half=False)
        dvec, r = pair_vectors(configuration, nl)
        n_pairs = nl.n_pairs

        if n_pairs and np.any(r <= 0.0):
            raise ValueError(
                "SOAP found a pair at zero separation; two atoms are coincident, "
                "which makes the neighbour direction undefined"
            )

        n_lm = (self.l_max + 1) ** 2
        c_pair = np.zeros((n_pairs, self.n_max, n_lm))
        dc = np.zeros((n_pairs, self.n_max, n_lm, 3)) if derivatives else None

        weights = None
        if self.species_weights is not None and n_pairs:
            if int(configuration.species.max(initial=0)) >= self.species_weights.size:
                raise ValueError(
                    "species_weights is shorter than the number of species present"
                )
            weights = self.species_weights[configuration.species[nl.j]]

        for lo in range(0, n_pairs, self.chunk_size):
            hi = min(lo + self.chunk_size, n_pairs)
            contrib, dcontrib = self._pair_expansion(dvec[lo:hi], r[lo:hi], derivatives)
            if weights is not None:
                contrib = contrib * weights[lo:hi, None, None]
                if derivatives:
                    dcontrib = dcontrib * weights[lo:hi, None, None, None]
            c_pair[lo:hi] = contrib
            if derivatives:
                dc[lo:hi] = dcontrib

        c = segment_sum(c_pair, nl.i, n_atoms)
        features, dfeat = self._power_spectrum(c, dc, nl.i if n_pairs else None, derivatives)

        if not derivatives:
            return DescriptorOutput(features=features)

        # Self term: moving atom i moves the origin of every one of its
        # neighbour vectors, so dp_i/dr_i = -sum_p dp_i/dd_p.  A self-image
        # pair (i, i, shift) contributes +X as a neighbour and -X here, and the
        # two cancel exactly -- correct, because translating atom i translates
        # both ends of that vector and leaves the environment unchanged.
        self_deriv = -segment_sum(dfeat, nl.i, n_atoms)

        pair_i = np.concatenate([nl.i, np.arange(n_atoms, dtype=np.int32)])
        pair_j = np.concatenate([nl.j, np.arange(n_atoms, dtype=np.int32)])
        derivs = np.concatenate([dfeat, self_deriv], axis=0)
        return DescriptorOutput(
            features=features, derivatives=derivs, pair_i=pair_i, pair_j=pair_j
        )

    def _power_spectrum(self, c, dc, pair_i, derivatives):
        """Contract ``c_nlm`` into the invariant power spectrum.

        Parameters
        ----------
        c : ndarray, shape (N, n_max, (l_max+1)**2)
        dc : ndarray, shape (P, n_max, (l_max+1)**2, 3) or None
        pair_i : ndarray, shape (P,) or None
            Central atom of each pair, used to gather ``c`` per pair.
        derivatives : bool

        Returns
        -------
        features : ndarray, shape (N, n_features)
        dfeatures : ndarray, shape (P, n_features, 3) or None
        """
        n_atoms = c.shape[0]
        n_pair_terms = self._pair_n.size
        features = np.zeros((n_atoms, self.n_features))
        n_pairs = 0 if dc is None else dc.shape[0]
        dfeatures = np.zeros((n_pairs, self.n_features, 3)) if derivatives else None

        if derivatives and n_pairs:
            c_at_pair = c[pair_i]  # (P, n_max, LM)

        for l in range(self.l_max + 1):
            lo, hi = l * l, (l + 1) ** 2
            scale = 1.0 / math.sqrt(2 * l + 1)
            block = slice(l * n_pair_terms, (l + 1) * n_pair_terms)

            cl = c[:, :, lo:hi]  # (N, n_max, 2l+1)
            p_full = np.einsum("anm,aNm->anN", cl, cl, optimize=True) * scale
            features[:, block] = p_full[:, self._pair_n, self._pair_m]

            if derivatives and n_pairs:
                dcl = dc[:, :, lo:hi, :]  # (P, n_max, 2l+1, 3)
                ccl = c_at_pair[:, :, lo:hi]  # (P, n_max, 2l+1)
                # d/dx of sum_m c_n c_n' = (dc_n) c_n' + c_n (dc_n'); the second
                # term is the transpose of the first in (n, n').
                t = np.einsum("pnmk,pNm->pnNk", dcl, ccl, optimize=True)
                t = (t + t.transpose(0, 2, 1, 3)) * scale
                dfeatures[:, block, :] = t[:, self._pair_n, self._pair_m, :]

        if not self.normalize:
            return features, dfeatures

        norms = np.linalg.norm(features, axis=1)
        # An empty environment gives p = 0, which has no unit-length
        # representative; leave it at zero rather than manufacturing a direction.
        safe = np.where(norms > 0.0, norms, 1.0)
        unit = features / safe[:, None]
        if derivatives and n_pairs:
            # (1 - p_hat p_hat^T) / ||p||  --  the projection term that a
            # normalised descriptor's derivative acquires.
            u_at_pair = unit[pair_i]
            proj = np.einsum("pd,pdk->pk", u_at_pair, dfeatures, optimize=True)
            dfeatures = (
                dfeatures - u_at_pair[:, :, None] * proj[:, None, :]
            ) / safe[pair_i][:, None, None]
        return unit, dfeatures
